### ISSUE TITLE
spaces added to align

### ISSUE THREAD

**Issue by bensworth** [lukeolson/clean-latex-to-arxiv#4]
I just did a git pull and ran parxiv and the new version seems to be adding space in weird spots. E.g., the stripped version looks like
```

\begin{align}\label{eq:P_gamma}
\mathcal{P}_\gamma &\coloneqq
	\left[\eta I - \widehat{\mathcal{L}}_2 + \beta^2 (\eta I - \widehat{\mathcal{L}}_1)^{-1}\right]
	(\gamma I- \widehat{\mathcal{L}}_2)^{-1} \\


& = \left[ (\eta^2+\beta^2) I - \eta (\widehat{\mathcal{L}}_1 + \widehat{\mathcal{L}}_2) +
		\widehat{\mathcal{L}}_2\widehat{\mathcal{L}}_1 \right]
		(\eta I- \widehat{\mathcal{L}}_1)^{-1}(\gamma I- \widehat{\mathcal{L}}_2)^{-1}.
		\nonumber
\end{align}
```
which does not compile. Can confirm this does not happen if I revert to this commit https://github.com/lukeolson/clean-latex-to-arxiv/commit/f0cb22e2cb291301275b2c4a74e875783a4faa49.

**Comment by lukeolson** [comment]
Can you drop in the original and I'll take a look.

**Comment by lukeolson** [comment]
@bensworth see if that fixes it for you.  I added your example as a unit tests as well (thanks!)
